version: "3.9"
services:
  api:
    build: api
    container_name: api_server
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: db
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - .data:/data

